### ISSUE TITLE
Fix tests for 0.8.2 release

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#10]
1. veles.znicz.tests.functional.test_cifar_all2all.TestCifarAll2All.test_cifar_all2all
2. veles.znicz.tests.functional.test_cifar_caffe.TestCifarCaffe.test_cifar_caffe 
3. veles.znicz.tests.functional.test_mnist7.TestMnist7.test_mnist7

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/46/1)
for change [46](https://velesnet.ml/gerrit/#/c/46) which triggered build [2566](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2566/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/47/1)
for change [47](https://velesnet.ml/gerrit/#/c/47) which triggered build [2567](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2567/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/46/2)
for change [46](https://velesnet.ml/gerrit/#/c/46) which triggered build [2568](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2568/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/46/3)
for change [46](https://velesnet.ml/gerrit/#/c/46) which triggered build [2569](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2569/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/47/1)
for change [47](https://velesnet.ml/gerrit/#/c/47) which triggered build [2570](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2570/)

**Comment by vmarkovtsev** [comment]
Vadim Markovtsev created new patchset [1](https://velesnet.ml/gerrit/#/c/51/1)
for change [51](https://velesnet.ml/gerrit/#/c/51) which triggered build [2571](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2571/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/59/1)
for change [59](https://velesnet.ml/gerrit/#/c/59) which triggered build [2575](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2575/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/67/1)
for change [67](https://velesnet.ml/gerrit/#/c/67) which triggered build [2578](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2578/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/76/1)
for change [76](https://velesnet.ml/gerrit/#/c/76) which triggered build [2584](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2584/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/90/1)
for change [90](https://velesnet.ml/gerrit/#/c/90) which triggered build [2588](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2588/)

**Comment by vmarkovtsev** [comment]
Vadim Markovtsev created new patchset [1](https://velesnet.ml/gerrit/#/c/102/1)
for change [102](https://velesnet.ml/gerrit/#/c/102) which triggered build [2591](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2591/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/108/1)
for change [108](https://velesnet.ml/gerrit/#/c/108) which triggered build [2598](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2598/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/108/2)
for change [108](https://velesnet.ml/gerrit/#/c/108) which triggered build [2599](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2599/)
