### ISSUE TITLE
Fix Evaluator and Decision after recent refactoring

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#12]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/60/1)
for change [60](https://velesnet.ml/gerrit/#/c/60) which triggered build [2576](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2576/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/64/1)
for change [64](https://velesnet.ml/gerrit/#/c/64) which triggered build [2577](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2577/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/145/1)
for change [145](https://velesnet.ml/gerrit/#/c/145) which triggered build [2645](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2645/)
