### ISSUE TITLE
Fix forward extraction. Add forward extraction example

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#15]
https://github.com/Samsung/veles/issues/20

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/73/1)
for change [73](https://velesnet.ml/gerrit/#/c/73) which triggered build [2580](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2580/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/74/1)
for change [74](https://velesnet.ml/gerrit/#/c/74) which triggered build [2581](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2581/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/75/1)
for change [75](https://velesnet.ml/gerrit/#/c/75) which triggered build [2582](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2582/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/75/2)
for change [75](https://velesnet.ml/gerrit/#/c/75) which triggered build [2583](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2583/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/101/1)
for change [101](https://velesnet.ml/gerrit/#/c/101) which triggered build [2590](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2590/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/103/1)
for change [103](https://velesnet.ml/gerrit/#/c/103) which triggered build [2592](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2592/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/104/1)
for change [104](https://velesnet.ml/gerrit/#/c/104) which triggered build [2593](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2593/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/75/3)
for change [75](https://velesnet.ml/gerrit/#/c/75) which triggered build [2594](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2594/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/105/1)
for change [105](https://velesnet.ml/gerrit/#/c/105) which triggered build [2595](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2595/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/75/4)
for change [75](https://velesnet.ml/gerrit/#/c/75) which triggered build [2596](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2596/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/106/1)
for change [106](https://velesnet.ml/gerrit/#/c/106) which triggered build [2597](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2597/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/103/2)
for change [103](https://velesnet.ml/gerrit/#/c/103) which triggered build [2600](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2600/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/104/2)
for change [104](https://velesnet.ml/gerrit/#/c/104) which triggered build [2601](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2601/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/106/2)
for change [106](https://velesnet.ml/gerrit/#/c/106) which triggered build [2602](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2602/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [5](https://velesnet.ml/gerrit/#/c/75/5)
for change [75](https://velesnet.ml/gerrit/#/c/75) which triggered build [2603](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2603/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/106/3)
for change [106](https://velesnet.ml/gerrit/#/c/106) which triggered build [2606](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2606/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/103/3)
for change [103](https://velesnet.ml/gerrit/#/c/103) which triggered build [2614](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2614/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/103/4)
for change [103](https://velesnet.ml/gerrit/#/c/103) which triggered build [2615](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2615/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [5](https://velesnet.ml/gerrit/#/c/103/5)
for change [103](https://velesnet.ml/gerrit/#/c/103) which triggered build [2625](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2625/)
