### ISSUE TITLE
Fix incorrect output of ForwardTanh with numpy backend

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles.znicz#17]

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/88/1)
for change [88](https://velesnet.ml/gerrit/#/c/88) which triggered build [2586](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2586/)
