### ISSUE TITLE
Fix automatically downloading of files. Set correct paths for data

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#19]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/112/1)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2604](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2604/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/112/2)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2607](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2607/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/112/3)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2608](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2608/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/112/4)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2609](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2609/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/113/1)
for change [113](https://velesnet.ml/gerrit/#/c/113) which triggered build [2610](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2610/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/114/1)
for change [114](https://velesnet.ml/gerrit/#/c/114) which triggered build [2611](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2611/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/113/2)
for change [113](https://velesnet.ml/gerrit/#/c/113) which triggered build [2612](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2612/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/113/3)
for change [113](https://velesnet.ml/gerrit/#/c/113) which triggered build [2613](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2613/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [5](https://velesnet.ml/gerrit/#/c/112/5)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2616](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2616/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/115/1)
for change [115](https://velesnet.ml/gerrit/#/c/115) which triggered build [2617](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2617/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/115/2)
for change [115](https://velesnet.ml/gerrit/#/c/115) which triggered build [2618](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2618/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [6](https://velesnet.ml/gerrit/#/c/112/6)
for change [112](https://velesnet.ml/gerrit/#/c/112) which triggered build [2626](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2626/)
