### ISSUE TITLE
Rename RpropAll2All to GD. Move gradient unit factory to tests

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#22]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/118/1)
for change [118](https://velesnet.ml/gerrit/#/c/118) which triggered build [2619](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2619/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/120/1)
for change [120](https://velesnet.ml/gerrit/#/c/120) which triggered build [2621](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2621/)
