### ISSUE TITLE
Fixed tests after recent refactoring

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#24]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/125/1)
for change [125](https://velesnet.ml/gerrit/#/c/125) which triggered build [2629](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2629/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/125/2)
for change [125](https://velesnet.ml/gerrit/#/c/125) which triggered build [2630](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2630/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/129/1)
for change [129](https://velesnet.ml/gerrit/#/c/129) which triggered build [2634](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2634/)
