### ISSUE TITLE
Refactor mnist forward after adding function for change of units

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#25]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/128/1)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2631](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2631/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/128/2)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2632](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2632/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/128/3)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2633](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2633/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/128/4)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2635](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2635/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [5](https://velesnet.ml/gerrit/#/c/128/5)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2636](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2636/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [6](https://velesnet.ml/gerrit/#/c/128/6)
for change [128](https://velesnet.ml/gerrit/#/c/128) which triggered build [2637](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2637/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/132/1)
for change [132](https://velesnet.ml/gerrit/#/c/132) which triggered build [2638](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2638/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/132/2)
for change [132](https://velesnet.ml/gerrit/#/c/132) which triggered build [2639](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2639/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/137/1)
for change [137](https://velesnet.ml/gerrit/#/c/137) which triggered build [2642](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2642/)
