### ISSUE TITLE
Update snapshots in Amazon

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#27]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/141/1)
for change [141](https://velesnet.ml/gerrit/#/c/141) which triggered build [2643](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2643/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/187/1)
for change [187](https://velesnet.ml/gerrit/#/c/187) which triggered build [2669](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2669/)
