### ISSUE TITLE
Fix ImagenetAE fine tuning and loader

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#3]
Data is in a new format after refactoring preparation_imagenet, so we need to fix loader in ImagenetAE. And plotters does not work at fine tuning stage.

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/36/1)
for change [36](https://velesnet.ml/gerrit/#/c/36) which triggered build [2558](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2558/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/37/1)
for change [37](https://velesnet.ml/gerrit/#/c/37) which triggered build [2559](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2559/)
