### ISSUE TITLE
Add Stl10 functional test and fix Stl10 Workflow

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#31]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/147/1)
for change [147](https://velesnet.ml/gerrit/#/c/147) which triggered build [2646](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2646/)
