### ISSUE TITLE
Change automatic random distribution for weights of fully connected units

### ISSUE THREAD

**Issue by ajkxyz** [Samsung/veles.znicz#32]

**Comment by vmarkovtsev** [comment]
Alexey Kazantsev created new patchset [1](https://velesnet.ml/gerrit/#/c/148/1)
for change [148](https://velesnet.ml/gerrit/#/c/148) which triggered build [2647](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2647/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/173/1)
for change [173](https://velesnet.ml/gerrit/#/c/173) which triggered build [2664](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2664/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/173/2)
for change [173](https://velesnet.ml/gerrit/#/c/173) which triggered build [2665](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2665/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/175/1)
for change [175](https://velesnet.ml/gerrit/#/c/175) which triggered build [2666](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2666/)
