### ISSUE TITLE
Fix tests for release 0.9.4

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#34]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/155/1)
for change [155](https://velesnet.ml/gerrit/#/c/155) which triggered build [2650](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2650/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/157/1)
for change [157](https://velesnet.ml/gerrit/#/c/157) which triggered build [2651](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2651/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/160/1)
for change [160](https://velesnet.ml/gerrit/#/c/160) which triggered build [2652](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2652/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/162/1)
for change [162](https://velesnet.ml/gerrit/#/c/162) which triggered build [2654](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2654/)
