### ISSUE TITLE
Add Imagenet forward propagation 

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#35]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/161/1)
for change [161](https://velesnet.ml/gerrit/#/c/161) which triggered build [2653](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2653/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/164/1)
for change [164](https://velesnet.ml/gerrit/#/c/164) which triggered build [2655](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2655/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/164/2)
for change [164](https://velesnet.ml/gerrit/#/c/164) which triggered build [2656](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2656/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/164/3)
for change [164](https://velesnet.ml/gerrit/#/c/164) which triggered build [2657](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2657/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/167/1)
for change [167](https://velesnet.ml/gerrit/#/c/167) which triggered build [2658](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2658/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/167/2)
for change [167](https://velesnet.ml/gerrit/#/c/167) which triggered build [2659](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2659/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/168/1)
for change [168](https://velesnet.ml/gerrit/#/c/168) which triggered build [2660](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2660/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/171/1)
for change [171](https://velesnet.ml/gerrit/#/c/171) which triggered build [2663](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2663/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/196/1)
for change [196](https://velesnet.ml/gerrit/#/c/196) which triggered build [2670](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2670/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/198/1)
for change [198](https://velesnet.ml/gerrit/#/c/198) which triggered build [2671](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2671/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/219/1)
for change [219](https://velesnet.ml/gerrit/#/c/219) which triggered build [2679](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2679/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/219/1)
for change [219](https://velesnet.ml/gerrit/#/c/219) which triggered build [2683](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2683/)
