### ISSUE TITLE
Change suffix of snapshot

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#36]
Remove "none" suffix if there is no samples in some sets (test, validation, train). Add "test" results to the suffix

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/182/1)
for change [182](https://velesnet.ml/gerrit/#/c/182) which triggered build [2668](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2668/)
