### ISSUE TITLE
Add Network-in-Network model for CIFAR10 and Imagenet

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#38]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/215/1)
for change [215](https://velesnet.ml/gerrit/#/c/215) which triggered build [2674](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2674/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/216/1)
for change [216](https://velesnet.ml/gerrit/#/c/216) which triggered build [2675](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2675/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/218/1)
for change [218](https://velesnet.ml/gerrit/#/c/218) which triggered build [2678](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2678/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/218/2)
for change [218](https://velesnet.ml/gerrit/#/c/218) which triggered build [2681](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2681/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/218/3)
for change [218](https://velesnet.ml/gerrit/#/c/218) which triggered build [2682](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2682/)
