### ISSUE TITLE
Add Channels forward propagation

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#39]

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/220/1)
for change [220](https://velesnet.ml/gerrit/#/c/220) which triggered build [2680](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2680/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [4](https://velesnet.ml/gerrit/#/c/220/4)
for change [220](https://velesnet.ml/gerrit/#/c/220) which triggered build [2684](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2684/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [5](https://velesnet.ml/gerrit/#/c/220/5)
for change [220](https://velesnet.ml/gerrit/#/c/220) which triggered build [2685](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2685/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/224/1)
for change [224](https://velesnet.ml/gerrit/#/c/224) which triggered build [2687](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2687/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/224/1)
for change [224](https://velesnet.ml/gerrit/#/c/224) which triggered build [2688](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2688/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/224/1)
for change [224](https://velesnet.ml/gerrit/#/c/224) which triggered build [2689](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2689/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/231/1)
for change [231](https://velesnet.ml/gerrit/#/c/231) which triggered build [2690](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2690/)
