### ISSUE TITLE
Add unique unit names in standard workflow

### ISSUE THREAD

**Issue by Lyubava** [Samsung/veles.znicz#9]
Currently unit's name is class name by default and workflow[name] returns list with units with one name. Need to add unique unit's name by default in standard workflow.

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [1](https://velesnet.ml/gerrit/#/c/122/1)
for change [122](https://velesnet.ml/gerrit/#/c/122) which triggered build [2622](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2622/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [2](https://velesnet.ml/gerrit/#/c/122/2)
for change [122](https://velesnet.ml/gerrit/#/c/122) which triggered build [2623](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2623/)

**Comment by vmarkovtsev** [comment]
Lyubov created new patchset [3](https://velesnet.ml/gerrit/#/c/122/3)
for change [122](https://velesnet.ml/gerrit/#/c/122) which triggered build [2624](http://velesnet.ml/jenkins/job/VELES_Python_Commit_Znicz/2624/)
